# Release notes template for GitHub
# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

changelog:
  categories:
    - title: '✨ Exciting New Features'
      labels:
        - '*'
    - title: '🚀 New Features'
      labels:
        - '*'
    - title: '🐛 Bug Fixes'
      labels:
        - '*'
    - title: '📦 Dependencies'
      labels:
        - '*'
    - title: '🔧 Maintenance'
      labels:
        - '*'
    - title: '⚙️ Other Changes'
      labels:
        - '*'