version: "2"

run:
  timeout: 10s

linters:
  default: all

  disable:
    - depguard # currently we don't use other modules
    - wsl # too noisy
    - wsl_v5 # new version of wsl linter
    - ireturn # causes "returns generic interface (V) of type param comparable"
    - exhaustruct # not needed, this module is small and simple

formatters:
  enable:
    - gci
    - gofmt
    - goimports
    - gofumpt

  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/kiteggrad)
        - localmodule
        - blank
        - dot
