name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
            go-version-file: 'go.mod'

      - name: Set up dependencies
        run: |
            go install github.com/go-task/task/v3/cmd/task@latest
            task deps

      - name: Lint
        run: task lint
      
      - name: Test
        run: task test

      - name: Upload Coverage
        uses: codecov/codecov-action@v5
        continue-on-error: true
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./.coverage.out
